version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    container_name: app
    hostname: app
    restart: always
    volumes:
      - ./src/:/usr/src/app/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./app/environment.env
    networks:
      django_net:
        ipv4_address: 10.20.30.1

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: server
    hostname: server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./server/environment.env
    ports:
      - 8080:8080
    networks:
      django_net:
        ipv4_address: 10.20.30.2

  db:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    container_name: db
    hostname: db
    restart: always
    env_file:
      - ./db/environment.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "ticmagicalline" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      django_net:
        ipv4_address: 10.20.30.3

networks:
  django_net:
    ipam:
      config:
        - subnet: 10.20.30.0/24
          gateway: 10.20.30.254
